# -*- coding: utf-8 -*-
"""Salary Data sheet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10iRfQbOw4kts1qSW4mqfyb2kG0fWNcDf
"""

import pandas as pd

df=pd.read_csv('/content/Salary_Dataset_DataScienceLovers.csv')
df.head()

df.isnull().sum()

company_name_mode = df['Company Name'].mode()[0]
df['Company Name'].fillna(company_name_mode, inplace=True)
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Identify categorical columns
categorical_cols = ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']

# Apply Label Encoding to each categorical column
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

df.head()

X = df.drop('Salary', axis=1)
y = df['Salary']

print('Input features (X) head:')
display(X.head())
print('\nTarget variable (y) head:')
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Shape of X_train:', X_train.shape)
print('Shape of X_test:', X_test.shape)
print('Shape of y_train:', y_train.shape)
print('Shape of y_test:', y_test.shape)

"""### 1. Linear Regression Model"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# Initialize and train the Linear Regression model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_linear = linear_reg_model.predict(X_test)

# Evaluate the model
mae_linear = mean_absolute_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)

print(f'Linear Regression Mean Absolute Error: {mae_linear:.2f}')
print(f'Linear Regression R-squared Score: {r2_linear:.2f}')

"""### 2. Decision Tree Regression Model"""

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)
decision_tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dtree = decision_tree_model.predict(X_test)

# Evaluate the model
mae_dtree = mean_absolute_error(y_test, y_pred_dtree)
r2_dtree = r2_score(y_test, y_pred_dtree)

print(f'Decision Tree Regressor Mean Absolute Error: {mae_dtree:.2f}')
print(f'Decision Tree Regressor R-squared Score: {r2_dtree:.2f}')

"""### 3. Random Forest Regression Model"""

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the Random Forest Regressor model
random_forest_model = RandomForestRegressor(n_estimators=100, random_state=42)
random_forest_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = random_forest_model.predict(X_test)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f'Random Forest Regressor Mean Absolute Error: {mae_rf:.2f}')
print(f'Random Forest Regressor R-squared Score: {r2_rf:.2f}')

"""### 4. Support Vector Machine (SVM) Regression Model"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
import numpy as np

# Scale the features for SVM (important for performance)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train the SVR model (using a linear kernel for potentially faster training)
# Note: SVR can be computationally intensive and may require hyperparameter tuning
# For demonstration, we'll use a linear kernel.
svr_model = SVR(kernel='linear')
svr_model.fit(X_train_scaled, y_train)

# Make predictions on the scaled test set
y_pred_svr = svr_model.predict(X_test_scaled)

# Evaluate the model
mae_svr = mean_absolute_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print(f'SVR Mean Absolute Error: {mae_svr:.2f}')
print(f'SVR R-squared Score: {r2_svr:.2f}')

"""### 5. K-Nearest Neighbors (KNN) Regression Model"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the KNN Regressor model
# n_neighbors is a hyperparameter to tune, starting with 5
knn_model = KNeighborsRegressor(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f'KNN Regressor Mean Absolute Error: {mae_knn:.2f}')
print(f'KNN Regressor R-squared Score: {r2_knn:.2f}')

"""### 6. Model Performance Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Create a DataFrame to store the performance metrics
performance_data = {
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'SVR', 'KNN'],
    'MAE': [mae_linear, mae_dtree, mae_rf, mae_svr, mae_knn],
    'R2 Score': [r2_linear, r2_dtree, r2_rf, r2_svr, r2_knn]
}

performance_df = pd.DataFrame(performance_data)
display(performance_df)

# Visualize MAE
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='MAE', data=performance_df, hue='Model', palette='viridis', legend=False)
plt.title('Mean Absolute Error (MAE) for Different Models')
plt.ylabel('Mean Absolute Error')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Visualize R2 Score
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='R2 Score', data=performance_df, hue='Model', palette='magma', legend=False)
plt.title('R-squared Score for Different Models')
plt.ylabel('R-squared Score')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import joblib
import os

# Create a directory to save the models if it doesn't exist
model_dir = 'trained_models'
os.makedirs(model_dir, exist_ok=True)

# Save the best performing model (SVR based on lowest MAE) and its scaler
joblib.dump(svr_model, os.path.join(model_dir, 'svr_model.pkl'))
joblib.dump(scaler, os.path.join(model_dir, 'scaler.pkl'))

print(f"SVR model and StandardScaler saved to '{model_dir}' directory.")

